import type { Tool, Category, Ecosystem, UseCase } from './types';

export const tools: Tool[] = [
  {
    id: 'express',
    name: 'Express',
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.18.2',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'The React Framework for the Web with hybrid static & server rendering',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '14.0.0',
  },
  {
    id: 'django',
    name: 'Django',
    description: 'High-level Python web framework that encourages rapid development',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.2.0',
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    description: 'Modern, fast web framework for building APIs with Python 3.7+',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'API security',
    riskLevel: 'Not scanned',
    defaultVersion: '0.104.0',
  },
  {
    id: 'wazuh',
    name: 'Wazuh',
    description: 'Open source security platform for threat detection and compliance',
    category: 'Security',
    ecosystem: 'npm',
    useCase: 'Vulnerability scanning',
    riskLevel: 'Not scanned',
    defaultVersion: '4.5.0',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Open source analytics and interactive visualization platform',
    category: 'Monitoring',
    ecosystem: 'npm',
    useCase: 'Observability',
    riskLevel: 'Not scanned',
    defaultVersion: '10.0.0',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    description: 'Next-generation ORM for Node.js and TypeScript',
    category: 'Database',
    ecosystem: 'npm',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '5.6.0',
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'Node.js client for Redis, the in-memory data structure store',
    category: 'Database',
    ecosystem: 'npm',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '4.6.0',
  },
  {
    id: 'authjs',
    name: 'Auth.js',
    description: 'Authentication for the Web. Free and open source.',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Auth',
    riskLevel: 'Not scanned',
    defaultVersion: '5.0.0',
  },
  {
    id: 'zod',
    name: 'Zod',
    description: 'TypeScript-first schema validation with static type inference',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'API security',
    riskLevel: 'Not scanned',
    defaultVersion: '3.22.0',
  },
  {
    id: 'lodash',
    name: 'lodash',
    description: 'A modern JavaScript utility library delivering modularity and performance',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '4.17.21',
  },
  {
    id: 'axios',
    name: 'axios',
    description: 'Promise based HTTP client for the browser and node.js',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'API client',
    riskLevel: 'Not scanned',
    defaultVersion: '1.6.0',
  },
];

export const categories: Category[] = [
  'Backend',
  'Frontend',
  'DevOps',
  'Security',
  'Monitoring',
  'Database',
  'AI',
];

export const ecosystems: Ecosystem[] = [
  'npm',
  'PyPI',
  'Go',
  'Maven',
  'crates.io',
  'RubyGems',
];

export const useCases: UseCase[] = [
  'Auth',
  'Logging',
  'Observability',
  'Vulnerability scanning',
  'CI/CD',
  'API security',
  'Web framework',
  'Database client',
  'Utility',
  'API client',
];
