import type { Tool } from './types';

export const tools: Tool[] = [
  // npm packages
  {
    id: 'express',
    name: 'express',
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.18.2',
    badge: 'Popular',
  },
  {
    id: 'next',
    name: 'next',
    description: 'The React framework for production with hybrid static & server rendering',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '14.2.0',
    badge: 'Popular',
  },
  {
    id: 'react',
    name: 'react',
    description: 'A JavaScript library for building user interfaces',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '18.2.0',
    badge: 'Essential',
  },
  {
    id: 'vue',
    name: 'vue',
    description: 'The progressive JavaScript framework for building UIs',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '3.4.21',
    badge: 'Popular',
  },
  {
    id: 'angular-core',
    name: '@angular/core',
    description: 'Angular - the core framework',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '17.3.0',
    badge: 'Popular',
  },
  {
    id: 'lodash',
    name: 'lodash',
    description: 'A modern JavaScript utility library delivering modularity, performance & extras',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '4.17.21',
    badge: 'Essential',
  },
  {
    id: 'axios',
    name: 'axios',
    description: 'Promise based HTTP client for the browser and Node.js',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'API client',
    riskLevel: 'Not scanned',
    defaultVersion: '1.6.8',
    badge: 'Popular',
  },
  {
    id: 'zod',
    name: 'zod',
    description: 'TypeScript-first schema validation with static type inference',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '3.22.4',
    badge: 'Trending',
  },
  {
    id: 'prisma',
    name: 'prisma',
    description: 'Next-generation ORM for Node.js and TypeScript',
    category: 'Database',
    ecosystem: 'npm',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '5.11.0',
    badge: 'Trending',
  },
  {
    id: 'auth-js',
    name: '@auth/core',
    description: 'Authentication for the Web. Simple. Secure. Extensible.',
    category: 'Security',
    ecosystem: 'npm',
    useCase: 'Auth',
    riskLevel: 'Not scanned',
    defaultVersion: '0.28.0',
    badge: 'Security',
  },
  {
    id: 'eslint',
    name: 'eslint',
    description: 'Find and fix problems in your JavaScript code',
    category: 'DevOps',
    ecosystem: 'npm',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '8.57.0',
    badge: 'Essential',
  },
  {
    id: 'jest',
    name: 'jest',
    description: 'Delightful JavaScript Testing with focus on simplicity',
    category: 'Testing',
    ecosystem: 'npm',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '29.7.0',
    badge: 'Popular',
  },
  {
    id: 'vite',
    name: 'vite',
    description: 'Next Generation Frontend Tooling',
    category: 'DevOps',
    ecosystem: 'npm',
    useCase: 'Package management',
    riskLevel: 'Not scanned',
    defaultVersion: '5.2.6',
    badge: 'Trending',
  },
  {
    id: 'typescript',
    name: 'typescript',
    description: 'TypeScript is a superset of JavaScript that compiles to clean JavaScript output',
    category: 'DevOps',
    ecosystem: 'npm',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '5.4.3',
    badge: 'Essential',
  },
  {
    id: 'webpack',
    name: 'webpack',
    description: 'A bundler for JavaScript and friends',
    category: 'DevOps',
    ecosystem: 'npm',
    useCase: 'Package management',
    riskLevel: 'Not scanned',
    defaultVersion: '5.91.0',
    badge: 'Infra',
  },
  {
    id: 'mongoose',
    name: 'mongoose',
    description: 'MongoDB object modeling for Node.js',
    category: 'Database',
    ecosystem: 'npm',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '8.2.2',
    badge: 'Popular',
  },
  {
    id: 'socket-io',
    name: 'socket.io',
    description: 'Realtime application framework for Node.js',
    category: 'Backend',
    ecosystem: 'npm',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.7.5',
  },
  {
    id: 'winston',
    name: 'winston',
    description: 'A logger for just about everything',
    category: 'Monitoring',
    ecosystem: 'npm',
    useCase: 'Logging',
    riskLevel: 'Not scanned',
    defaultVersion: '3.12.0',
  },
  // PyPI packages
  {
    id: 'django',
    name: 'django',
    description: 'The web framework for perfectionists with deadlines',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '5.0.3',
    badge: 'Popular',
  },
  {
    id: 'fastapi',
    name: 'fastapi',
    description: 'FastAPI framework, high performance, easy to learn, fast to code',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '0.110.0',
    badge: 'Trending',
  },
  {
    id: 'flask',
    name: 'flask',
    description: 'A lightweight WSGI web application framework',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '3.0.2',
    badge: 'Popular',
  },
  {
    id: 'requests',
    name: 'requests',
    description: 'Python HTTP for Humans',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'API client',
    riskLevel: 'Not scanned',
    defaultVersion: '2.31.0',
    badge: 'Essential',
  },
  {
    id: 'pandas',
    name: 'pandas',
    description: 'Powerful data structures for data analysis and manipulation',
    category: 'Data',
    ecosystem: 'PyPI',
    useCase: 'Data processing',
    riskLevel: 'Not scanned',
    defaultVersion: '2.2.1',
    badge: 'Essential',
  },
  {
    id: 'numpy',
    name: 'numpy',
    description: 'Fundamental package for array computing with Python',
    category: 'Data',
    ecosystem: 'PyPI',
    useCase: 'Data processing',
    riskLevel: 'Not scanned',
    defaultVersion: '1.26.4',
    badge: 'Essential',
  },
  {
    id: 'sqlalchemy',
    name: 'sqlalchemy',
    description: 'The Python SQL Toolkit and Object Relational Mapper',
    category: 'Database',
    ecosystem: 'PyPI',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '2.0.28',
    badge: 'Popular',
  },
  {
    id: 'celery',
    name: 'celery',
    description: 'Distributed Task Queue',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Deployment',
    riskLevel: 'Not scanned',
    defaultVersion: '5.3.6',
    badge: 'Infra',
  },
  {
    id: 'pytest',
    name: 'pytest',
    description: 'Simple powerful testing with Python',
    category: 'Testing',
    ecosystem: 'PyPI',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '8.1.1',
    badge: 'Essential',
  },
  {
    id: 'pydantic',
    name: 'pydantic',
    description: 'Data validation using Python type annotations',
    category: 'Backend',
    ecosystem: 'PyPI',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '2.6.4',
    badge: 'Trending',
  },
  {
    id: 'pytorch',
    name: 'torch',
    description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration',
    category: 'AI',
    ecosystem: 'PyPI',
    useCase: 'AI tooling',
    riskLevel: 'Not scanned',
    defaultVersion: '2.2.1',
    badge: 'Popular',
  },
  {
    id: 'tensorflow',
    name: 'tensorflow',
    description: 'An open source machine learning framework',
    category: 'AI',
    ecosystem: 'PyPI',
    useCase: 'AI tooling',
    riskLevel: 'Not scanned',
    defaultVersion: '2.16.1',
    badge: 'Popular',
  },
  // Go packages
  {
    id: 'gin',
    name: 'github.com/gin-gonic/gin',
    description: 'Gin is a HTTP web framework written in Go featuring a Martini-like API',
    category: 'Backend',
    ecosystem: 'Go',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '1.9.1',
    badge: 'Popular',
  },
  {
    id: 'fiber',
    name: 'github.com/gofiber/fiber',
    description: 'Express inspired web framework built on top of Fasthttp',
    category: 'Backend',
    ecosystem: 'Go',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '2.52.2',
    badge: 'Trending',
  },
  {
    id: 'cobra',
    name: 'github.com/spf13/cobra',
    description: 'A Commander for modern Go CLI interactions',
    category: 'CLI',
    ecosystem: 'Go',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '1.8.0',
    badge: 'Popular',
  },
  {
    id: 'zap',
    name: 'go.uber.org/zap',
    description: 'Blazing fast, structured, leveled logging in Go',
    category: 'Monitoring',
    ecosystem: 'Go',
    useCase: 'Logging',
    riskLevel: 'Not scanned',
    defaultVersion: '1.27.0',
  },
  {
    id: 'gorm',
    name: 'gorm.io/gorm',
    description: 'The fantastic ORM library for Golang',
    category: 'Database',
    ecosystem: 'Go',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '1.25.8',
    badge: 'Popular',
  },
  {
    id: 'echo',
    name: 'github.com/labstack/echo',
    description: 'High performance, extensible, minimalist Go web framework',
    category: 'Backend',
    ecosystem: 'Go',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.11.4',
  },
  // Maven packages
  {
    id: 'spring-core',
    name: 'org.springframework:spring-core',
    description: 'Spring Framework core, providing dependency injection features',
    category: 'Backend',
    ecosystem: 'Maven',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '6.1.5',
    badge: 'Popular',
  },
  {
    id: 'junit',
    name: 'org.junit.jupiter:junit-jupiter',
    description: 'JUnit 5 - The next generation of JUnit',
    category: 'Testing',
    ecosystem: 'Maven',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '5.10.2',
    badge: 'Essential',
  },
  {
    id: 'log4j-core',
    name: 'org.apache.logging.log4j:log4j-core',
    description: 'Apache Log4j Core',
    category: 'Monitoring',
    ecosystem: 'Maven',
    useCase: 'Logging',
    riskLevel: 'Not scanned',
    defaultVersion: '2.23.1',
    badge: 'Security',
  },
  {
    id: 'jackson-core',
    name: 'com.fasterxml.jackson.core:jackson-core',
    description: 'Core part of Jackson for JSON processing',
    category: 'Backend',
    ecosystem: 'Maven',
    useCase: 'Serialization',
    riskLevel: 'Not scanned',
    defaultVersion: '2.17.0',
  },
  // crates.io packages
  {
    id: 'serde',
    name: 'serde',
    description: 'A generic serialization/deserialization framework',
    category: 'Backend',
    ecosystem: 'crates.io',
    useCase: 'Serialization',
    riskLevel: 'Not scanned',
    defaultVersion: '1.0.197',
    badge: 'Essential',
  },
  {
    id: 'tokio',
    name: 'tokio',
    description: 'An event-driven, non-blocking I/O platform for writing asynchronous applications',
    category: 'Backend',
    ecosystem: 'crates.io',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '1.36.0',
    badge: 'Popular',
  },
  {
    id: 'clap',
    name: 'clap',
    description: 'A full featured, fast Command Line Argument Parser',
    category: 'CLI',
    ecosystem: 'crates.io',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '4.5.3',
    badge: 'Popular',
  },
  {
    id: 'actix-web',
    name: 'actix-web',
    description: 'Actix Web is a powerful, pragmatic, and extremely fast web framework for Rust',
    category: 'Backend',
    ecosystem: 'crates.io',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '4.5.1',
    badge: 'Trending',
  },
  // RubyGems packages
  {
    id: 'rails',
    name: 'rails',
    description: 'Full-stack web application framework for Ruby',
    category: 'Backend',
    ecosystem: 'RubyGems',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '7.1.3',
    badge: 'Popular',
  },
  {
    id: 'sidekiq',
    name: 'sidekiq',
    description: 'Simple, efficient background processing for Ruby',
    category: 'Backend',
    ecosystem: 'RubyGems',
    useCase: 'Deployment',
    riskLevel: 'Not scanned',
    defaultVersion: '7.2.2',
    badge: 'Infra',
  },
  {
    id: 'devise',
    name: 'devise',
    description: 'Flexible authentication solution for Rails with Warden',
    category: 'Security',
    ecosystem: 'RubyGems',
    useCase: 'Auth',
    riskLevel: 'Not scanned',
    defaultVersion: '4.9.3',
    badge: 'Security',
  },
  // Infrastructure tools
  {
    id: 'grafana',
    name: 'grafana',
    description: 'Open and composable observability and data visualization platform',
    category: 'Monitoring',
    ecosystem: 'Docker',
    useCase: 'Observability',
    riskLevel: 'Not scanned',
    defaultVersion: '10.4.1',
    badge: 'Infra',
  },
  {
    id: 'prometheus',
    name: 'prometheus',
    description: 'Monitoring system and time series database',
    category: 'Monitoring',
    ecosystem: 'Docker',
    useCase: 'Observability',
    riskLevel: 'Not scanned',
    defaultVersion: '2.51.0',
    badge: 'Infra',
  },
  {
    id: 'elasticsearch',
    name: 'elasticsearch',
    description: 'Distributed, RESTful search and analytics engine',
    category: 'Database',
    ecosystem: 'Docker',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '8.13.0',
    badge: 'Infra',
  },
  {
    id: 'redis',
    name: 'redis',
    description: 'In-memory data structure store, used as database, cache, and message broker',
    category: 'Database',
    ecosystem: 'Docker',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '7.2.4',
    badge: 'Essential',
  },
  {
    id: 'nginx',
    name: 'nginx',
    description: 'High-performance HTTP server and reverse proxy',
    category: 'Infrastructure',
    ecosystem: 'Docker',
    useCase: 'Deployment',
    riskLevel: 'Not scanned',
    defaultVersion: '1.25.4',
    badge: 'Infra',
  },
  {
    id: 'postgres',
    name: 'postgres',
    description: 'The most advanced open source relational database',
    category: 'Database',
    ecosystem: 'Docker',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '16.2',
    badge: 'Essential',
  },
  // GitHub Actions
  {
    id: 'actions-checkout',
    name: 'actions/checkout',
    description: 'Check out a Git repository at a particular version',
    category: 'DevOps',
    ecosystem: 'GitHub Actions',
    useCase: 'CI/CD',
    riskLevel: 'Not scanned',
    defaultVersion: '4.1.2',
    badge: 'Essential',
  },
  {
    id: 'actions-setup-node',
    name: 'actions/setup-node',
    description: 'Set up a specific version of Node.js in your workflow',
    category: 'DevOps',
    ecosystem: 'GitHub Actions',
    useCase: 'CI/CD',
    riskLevel: 'Not scanned',
    defaultVersion: '4.0.2',
  },
  // NuGet packages
  {
    id: 'newtonsoft-json',
    name: 'Newtonsoft.Json',
    description: 'Popular high-performance JSON framework for .NET',
    category: 'Backend',
    ecosystem: 'NuGet',
    useCase: 'Serialization',
    riskLevel: 'Not scanned',
    defaultVersion: '13.0.3',
    badge: 'Popular',
  },
  {
    id: 'entity-framework',
    name: 'Microsoft.EntityFrameworkCore',
    description: 'Entity Framework Core is a modern object-database mapper for .NET',
    category: 'Database',
    ecosystem: 'NuGet',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '8.0.3',
    badge: 'Popular',
  },
  // Packagist packages
  {
    id: 'laravel',
    name: 'laravel/laravel',
    description: 'The PHP Framework for Web Artisans',
    category: 'Backend',
    ecosystem: 'Packagist',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '11.0.0',
    badge: 'Popular',
  },
  {
    id: 'symfony',
    name: 'symfony/symfony',
    description: 'The Symfony PHP framework',
    category: 'Backend',
    ecosystem: 'Packagist',
    useCase: 'Web framework',
    riskLevel: 'Not scanned',
    defaultVersion: '7.0.5',
    badge: 'Popular',
  },
  // Security tools
  {
    id: 'snyk',
    name: 'snyk',
    description: 'Snyk CLI scans and monitors your projects for security vulnerabilities',
    category: 'Security',
    ecosystem: 'npm',
    useCase: 'Vulnerability scanning',
    riskLevel: 'Not scanned',
    defaultVersion: '1.1282.0',
    badge: 'Security',
  },
  {
    id: 'helmet',
    name: 'helmet',
    description: 'Help secure Express apps with various HTTP headers',
    category: 'Security',
    ecosystem: 'npm',
    useCase: 'API security',
    riskLevel: 'Not scanned',
    defaultVersion: '7.1.0',
    badge: 'Security',
  },
  {
    id: 'bcrypt',
    name: 'bcrypt',
    description: 'A library to help you hash passwords',
    category: 'Security',
    ecosystem: 'npm',
    useCase: 'Auth',
    riskLevel: 'Not scanned',
    defaultVersion: '5.1.1',
    badge: 'Security',
  },
  // Additional popular packages
  {
    id: 'tailwindcss',
    name: 'tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development',
    category: 'Frontend',
    ecosystem: 'npm',
    useCase: 'Utility',
    riskLevel: 'Not scanned',
    defaultVersion: '3.4.1',
    badge: 'Trending',
  },
  {
    id: 'drizzle-orm',
    name: 'drizzle-orm',
    description: 'Headless TypeScript ORM with SQL-like syntax',
    category: 'Database',
    ecosystem: 'npm',
    useCase: 'Database client',
    riskLevel: 'Not scanned',
    defaultVersion: '0.30.4',
    badge: 'New',
  },
  {
    id: 'openai',
    name: 'openai',
    description: 'Official OpenAI API library for JavaScript',
    category: 'AI',
    ecosystem: 'npm',
    useCase: 'AI tooling',
    riskLevel: 'Not scanned',
    defaultVersion: '4.29.2',
    badge: 'Trending',
  },
  {
    id: 'langchain',
    name: 'langchain',
    description: 'Building applications with LLMs through composability',
    category: 'AI',
    ecosystem: 'PyPI',
    useCase: 'AI tooling',
    riskLevel: 'Not scanned',
    defaultVersion: '0.1.12',
    badge: 'Trending',
  },
  {
    id: 'vitest',
    name: 'vitest',
    description: 'Blazing Fast Unit Test Framework',
    category: 'Testing',
    ecosystem: 'npm',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '1.4.0',
    badge: 'Trending',
  },
  {
    id: 'playwright',
    name: '@playwright/test',
    description: 'A framework for Web Testing and Automation',
    category: 'Testing',
    ecosystem: 'npm',
    useCase: 'Testing',
    riskLevel: 'Not scanned',
    defaultVersion: '1.42.1',
    badge: 'Trending',
  },
];

export function getToolByEcosystemAndName(ecosystem: string, name: string): Tool | undefined {
  return tools.find(
    (tool) => 
      tool.ecosystem.toLowerCase() === ecosystem.toLowerCase() && 
      tool.name.toLowerCase() === name.toLowerCase()
  );
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}
